"""A labelled corpus of small ontologies — the course's evaluation substrate.

Each entry carries **hand-authored** gold labels: the spectrum level the author
intended and the modelling defects the author deliberately injected. The labels
are *not* generated by the detectors in :mod:`oe_course.ontology`; instead
:func:`verify_corpus` checks that the detectors agree with the author, so a
regression in either the corpus or a detector shows up immediately.

This matters for what the Chapter 1 agent evaluation actually measures. The
deterministic metric asks "did the agent gather the right evidence and report it
faithfully?" — a tool-using agent's real job — while the LLM judge scores the
quality of the written justification. Keeping the gold independent of the
detectors keeps that first question honest.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent

_HEADER = """@prefix owl:  <http://www.w3.org/2002/07/owl#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix ex:   <http://example.org/oe/> .
"""


@dataclass(frozen=True)
class Artefact:
    """One labelled ontology in the corpus."""

    name: str
    turtle: str
    gold_level: str
    gold_smells: frozenset[str]
    note: str = ""
    #: Detectors whose findings are expected but not part of the graded label
    #: (e.g. a vocabulary that legitimately has no properties to annotate).
    tolerated_smells: frozenset[str] = field(default_factory=frozenset)


def _ttl(body: str) -> str:
    return _HEADER + body


# --------------------------------------------------------------------------- #
# Clean artefacts, one per spectrum level
# --------------------------------------------------------------------------- #
_COLOURS = _ttl("""
ex:ColourScheme a owl:Ontology .

ex:Red    a owl:Class ; skos:prefLabel "red"@en .
ex:Green  a owl:Class ; skos:prefLabel "green"@en .
ex:Blue   a owl:Class ; skos:prefLabel "blue"@en .
ex:Cyan   a owl:Class ; skos:prefLabel "cyan"@en .
""")

_ANIMALS = _ttl("""
ex:AnimalTaxonomy a owl:Ontology .

ex:Animal    a owl:Class ; rdfs:label "animal"@en .
ex:Mammal    a owl:Class ; rdfs:label "mammal"@en ; rdfs:subClassOf ex:Animal .
ex:Bird      a owl:Class ; rdfs:label "bird"@en ;   rdfs:subClassOf ex:Animal .
ex:Cat       a owl:Class ; rdfs:label "cat"@en ;    rdfs:subClassOf ex:Mammal .
ex:Dog       a owl:Class ; rdfs:label "dog"@en ;    rdfs:subClassOf ex:Mammal .
ex:Penguin   a owl:Class ; rdfs:label "penguin"@en ; rdfs:subClassOf ex:Bird .
""")

_FOOD = _ttl("""
ex:FoodThesaurus a owl:Ontology .

ex:Food      a owl:Class ; skos:prefLabel "food"@en ; rdfs:label "food"@en .
ex:Fruit     a owl:Class ; skos:prefLabel "fruit"@en ; rdfs:label "fruit"@en ;
             rdfs:subClassOf ex:Food ; skos:broader ex:Food .
ex:Apple     a owl:Class ; skos:prefLabel "apple"@en ; rdfs:label "apple"@en ;
             rdfs:subClassOf ex:Fruit ; skos:broader ex:Fruit ;
             skos:related ex:Cider .
ex:Cider     a owl:Class ; skos:prefLabel "cider"@en ; rdfs:label "cider"@en ;
             rdfs:subClassOf ex:Food ; skos:related ex:Apple .
""")

# --------------------------------------------------------------------------- #
# Defective artefacts — one injected defect each
# --------------------------------------------------------------------------- #
_CYCLE = _ttl("""
ex:CyclicOnt a owl:Ontology .

ex:Vehicle a owl:Class ; rdfs:label "vehicle"@en ; rdfs:subClassOf ex:Car .
ex:Car     a owl:Class ; rdfs:label "car"@en ;     rdfs:subClassOf ex:Vehicle .
ex:Lorry   a owl:Class ; rdfs:label "lorry"@en ;   rdfs:subClassOf ex:Vehicle .
""")

_PUNNING = _ttl("""
ex:SpeciesMuddle a owl:Ontology .

ex:Species a owl:Class ; rdfs:label "species"@en .
ex:Lion    a owl:Class ; rdfs:label "lion"@en ; rdfs:subClassOf ex:Animal ;
           rdf:type ex:Species .
ex:Tiger   a owl:Class ; rdfs:label "tiger"@en ; rdfs:subClassOf ex:Animal .
ex:Animal  a owl:Class ; rdfs:label "animal"@en .
""")

_INSTANCE = _ttl("""
ex:StaffMuddle a owl:Ontology .

ex:Person    a owl:Class ; rdfs:label "person"@en .
ex:Lecturer  a owl:Class ; rdfs:label "lecturer"@en ; rdfs:subClassOf ex:Person .
ex:mary      a owl:NamedIndividual ; rdfs:label "Mary"@en ;
             rdfs:subClassOf ex:Lecturer .
""")

_UNDECLARED = _ttl("""
ex:LooseEnds a owl:Ontology .

ex:Building a owl:Class ; rdfs:label "building"@en ; rdfs:subClassOf ex:Structure .
ex:House    a owl:Class ; rdfs:label "house"@en ;    rdfs:subClassOf ex:Building .
""")

_UNLABELLED = _ttl("""
ex:Opaque a owl:Ontology .

ex:C0001 a owl:Class .
ex:C0002 a owl:Class ; rdfs:subClassOf ex:C0001 .
ex:C0003 a owl:Class ; rdfs:subClassOf ex:C0001 .
""")

_BARE_PROPS = _ttl("""
ex:BareProperties a owl:Ontology .

ex:Document a owl:Class ; rdfs:label "document"@en .
ex:Author   a owl:Class ; rdfs:label "author"@en .
ex:Report   a owl:Class ; rdfs:label "report"@en ; rdfs:subClassOf ex:Document .
ex:Memo     a owl:Class ; rdfs:label "memo"@en ;   rdfs:subClassOf ex:Document .

ex:writtenBy a owl:ObjectProperty ; rdfs:label "written by"@en .
ex:cites     a owl:ObjectProperty ; rdfs:label "cites"@en ; rdfs:domain ex:Document .
""")

_MULTI = _ttl("""
ex:LegacyImport a owl:Ontology .

ex:Thing0    a owl:Class .
ex:Process   a owl:Class ; rdfs:label "process"@en ; rdfs:subClassOf ex:Activity .
ex:Activity  a owl:Class ; rdfs:label "activity"@en ; rdfs:subClassOf ex:Process .
ex:involves  a owl:ObjectProperty ; rdfs:label "involves"@en .
""")


def _awo_turtle() -> str:
    return (DATA_DIR / "awo.ttl").read_text(encoding="utf-8")


CORPUS: list[Artefact] = [
    Artefact(
        "awo",
        _awo_turtle(),
        "formal-ontology",
        frozenset(),
        "Keet's tutorial ontology: the clean positive control.",
    ),
    Artefact(
        "colours-vocab",
        _COLOURS,
        "controlled-vocabulary",
        frozenset(),
        "Named terms with SKOS labels and no structure at all.",
    ),
    Artefact(
        "animals-taxonomy",
        _ANIMALS,
        "taxonomy",
        frozenset({"no-disjointness"}),
        "A pure is-a hierarchy; nothing stops a cat from also being a bird.",
    ),
    Artefact(
        "food-thesaurus",
        _FOOD,
        "thesaurus",
        frozenset({"no-disjointness"}),
        "Adds SKOS broader/related on top of a hierarchy.",
    ),
    Artefact(
        "broken-cycle",
        _CYCLE,
        "taxonomy",
        frozenset({"subsumption-cycle", "no-disjointness"}),
        "Vehicle and Car subsume each other, collapsing them under a reasoner.",
    ),
    Artefact(
        "species-punning",
        _PUNNING,
        "taxonomy",
        frozenset({"class-as-individual", "no-disjointness"}),
        "Lion is both a class and an instance of Species.",
    ),
    Artefact(
        "staff-instance-confusion",
        _INSTANCE,
        "taxonomy",
        frozenset({"individual-as-class"}),
        "An individual placed in a subsumption axiom. Note there are no sibling "
        "classes here, so the disjointness detector correctly stays silent.",
    ),
    Artefact(
        "loose-ends",
        _UNDECLARED,
        "taxonomy",
        frozenset({"undeclared-term"}),
        "Refers to ex:Structure, which is never declared.",
    ),
    Artefact(
        "opaque-ids",
        _UNLABELLED,
        "taxonomy",
        frozenset({"missing-label", "no-disjointness"}),
        "Opaque identifiers with no labels: unreviewable by a domain expert.",
    ),
    Artefact(
        "bare-properties",
        _BARE_PROPS,
        "taxonomy",
        frozenset({"property-without-domain-or-range", "no-disjointness"}),
        "Object properties carrying no domain/range commitment.",
    ),
    Artefact(
        "legacy-import",
        _MULTI,
        "taxonomy",
        frozenset(
            {
                "subsumption-cycle",
                "missing-label",
                "property-without-domain-or-range",
            }
        ),
        "Several defects at once — the realistic case.",
    ),
]

BY_NAME = {a.name: a for a in CORPUS}


def get(name: str) -> Artefact:
    return BY_NAME[name]


def verify_corpus() -> list[str]:
    """Check every detector against the hand-authored labels.

    Returns a list of human-readable disagreements; empty means the corpus and
    the detectors agree. Notebooks run this as a self-test.
    """
    from oe_course import ontology as ont

    problems: list[str] = []
    for art in CORPUS:
        g = ont.load_graph(art.turtle)
        level = ont.classify_spectrum(g)["level"]
        if level != art.gold_level:
            problems.append(f"{art.name}: level detected {level!r}, gold {art.gold_level!r}")
        detected = set(ont.smell_summary(g)) - set(art.tolerated_smells)
        if detected != set(art.gold_smells):
            missing = set(art.gold_smells) - detected
            extra = detected - set(art.gold_smells)
            problems.append(
                f"{art.name}: smells missing={sorted(missing)} unexpected={sorted(extra)}"
            )
    return problems
