"""Validate the specification and regenerate CHECK_CATALOGUE.md.

    python build_docs.py

Fails loudly (exit 1) if the catalogue or the SysML models break one of the rules the
specification relies on:

* catalogue: unique ids, known families/methods/severities/stages/profiles, every
  adjudicated check has a deterministic candidate method, every check that can change a
  verdict (severity != info) names a mutation operator, adjudicated checks are capped
  below blocker;
* models: every requirement that is satisfied or verified exists, every requirement is
  satisfied or verified somewhere, every verification case referenced exists.

The SysML files are read with the repo's own subset reader
(architecture/graphrag_agent/sysml_model.py), so the same diagrams tooling applies.
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
AGENT = HERE.parent
REPO = AGENT.parents[2]
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(REPO / "architecture" / "graphrag_agent"))

import check_catalogue as cat  # noqa: E402

def validate_catalogue() -> list[str]:
    errors = []
    ids = Counter(c.id for c in cat.CHECKS)
    errors += [f"duplicate id {i}" for i, n in ids.items() if n > 1]
    families = {f.code for f in cat.FAMILIES}
    for c in cat.CHECKS:
        if not c.id.startswith(c.family + "-"):
            errors.append(f"{c.id}: id prefix does not match family {c.family}")
        if c.family not in families:
            errors.append(f"{c.id}: unknown family {c.family}")
        if c.method not in cat.METHODS:
            errors.append(f"{c.id}: unknown method {c.method}")
        if c.severity not in cat.SEVERITIES:
            errors.append(f"{c.id}: unknown severity {c.severity}")
        if c.adjudication not in cat.ADJUDICATION:
            errors.append(f"{c.id}: unknown adjudication {c.adjudication}")
        if c.stage not in cat.STAGES:
            errors.append(f"{c.id}: unknown stage {c.stage}")
        for p in c.applies:
            if p not in cat.PROFILES:
                errors.append(f"{c.id}: unknown profile {p}")
        if c.severity != "info" and not c.mutation and c.adjudication != "human":
            errors.append(f"{c.id}: can change a verdict but has no mutation operator")
        if c.adjudication == "llm" and c.severity == "blocker":
            errors.append(f"{c.id}: adjudicated checks are capped at major (OVA-T03)")
    return errors


def validate_models() -> tuple[list[str], dict]:
    try:
        import sysml_model as sm
    except ImportError:
        return ["architecture/graphrag_agent/sysml_model.py not found"], {}
    models = sm.parse_all(AGENT / "models")
    reqs, cases, rels = set(), set(), []
    stats = {}
    for m in models:
        stats[m.path.name] = Counter(e.kind for e in m.root.descendants())
        reqs |= {e.ident for e in m.by_kind("requirement def") if e.ident}
        cases |= {e.ident for e in m.by_kind("verification def") if e.ident}
        rels += m.relations
    errors = []
    satisfied = {r.target for r in rels if r.kind == "satisfy"}
    verified = {r.target for r in rels if r.kind == "verify"}
    for r in rels:
        if r.kind == "satisfy" and r.target not in reqs:
            errors.append(f"satisfy references unknown requirement {r.target}")
        if r.kind == "verify":
            if r.target not in reqs:
                errors.append(f"verify references unknown requirement {r.target}")
            if r.source not in cases:
                errors.append(f"verify references unknown case {r.source}")
    for r in sorted(reqs - satisfied - verified):
        errors.append(f"requirement {r} is neither satisfied nor verified")
    stats["_trace"] = {"requirements": len(reqs), "satisfied": len(satisfied & reqs),
                       "verified": len(verified & reqs), "cases": len(cases)}
    return errors, stats


def _md_escape(text: str) -> str:
    return text.replace("|", "\\|")


def render_catalogue() -> str:
    checks = cat.CHECKS
    by_family = {f.code: [c for c in checks if c.family == f.code] for f in cat.FAMILIES}
    sev = Counter(c.severity for c in checks)
    meth = Counter(c.method for c in checks)
    adj = Counter(c.adjudication for c in checks)
    stage = Counter(c.stage for c in checks)
    oops = sorted({r for c in checks for r in c.refs if r.startswith("OOPS")},
                  key=lambda r: int(r.rsplit("P", 1)[1]))

    out = [
        "# Check Catalogue",
        "",
        "> Generated by `spec/build_docs.py` from `spec/check_catalogue.py` -- do not edit by hand.",
        "",
        f"**{len(checks)} checks in {len(cat.FAMILIES)} families.** "
        f"Deterministic: {adj['none']} · LLM-adjudicated candidates: {adj['llm']} · "
        f"human-adjudicated: {adj['human']}.",
        "",
        "| severity | count |  | method | count |  | stage | count |",
        "|---|---|---|---|---|---|---|---|",
    ]
    rows = max(len(cat.SEVERITIES), len(cat.METHODS), len(cat.STAGES))
    sevs, meths, stages = list(cat.SEVERITIES), list(cat.METHODS), list(cat.STAGES)
    for i in range(rows):
        s = f"{sevs[i]} | {sev[sevs[i]]}" if i < len(sevs) else " | "
        m = f"{meths[i]} | {meth[meths[i]]}" if i < len(meths) else " | "
        g = f"{stages[i]} | {stage[stages[i]]}" if i < len(stages) else " | "
        out.append(f"| {s} | | {m} | | {g} |")
    out += [
        "",
        "**Legend.** *Method* names the engine that generates findings (or candidates). "
        "*Adj.* = adjudication: `none` (decidable; the critic overrides the model), "
        "`llm` (deterministic candidates, LLM labels true/false positive, severity capped at "
        "major), `human`. *Stage*: " + "; ".join(f"`{k}` {v}" for k, v in cat.STAGES.items()) +
        ". *Mutation* is the S2 fault-injection operator whose mutants the check must kill.",
        "",
        f"OOPS! pitfalls covered: {', '.join(oops)}.",
        "",
        "## Families",
        "",
        "| code | family | checks | purpose | reference oracles |",
        "|---|---|---|---|---|",
    ]
    for f in cat.FAMILIES:
        out.append(f"| [{f.code}](#{f.code.lower()}) | {f.title} | {len(by_family[f.code])} | "
                   f"{f.purpose} | {', '.join(f.oracles) or '--'} |")
    for f in cat.FAMILIES:
        out += ["", f"## {f.code}", "", f"**{f.title}.** {f.purpose}", "",
                "| id | check | sev. | method | adj. | applies | stage | mutation |",
                "|---|---|---|---|---|---|---|---|"]
        for c in by_family[f.code]:
            out.append(f"| {c.id} | **{_md_escape(c.title)}** | {c.severity} | {c.method} | "
                       f"{c.adjudication} | {', '.join(c.applies)} | {c.stage} | "
                       f"{c.mutation or '--'} |")
        out.append("")
        for c in by_family[f.code]:
            extra = []
            if c.refs:
                extra.append("refs: " + "; ".join(c.refs))
            if c.params:
                extra.append("params: " + ", ".join(f"`{k}={v}`" for k, v in c.params.items()))
            tail = f" *({' · '.join(extra)})*" if extra else ""
            out.append(f"- **{c.id}** -- {c.detects} *Why:* {c.rationale}{tail}")
    return "\n".join(out) + "\n"


def main() -> int:
    errors = validate_catalogue()
    model_errors, stats = validate_models()
    errors += model_errors
    (AGENT / "CHECK_CATALOGUE.md").write_text(render_catalogue(), encoding="utf-8")
    print(f"catalogue: {len(cat.CHECKS)} checks, {len(cat.FAMILIES)} families")
    for name, counts in stats.items():
        print(f"  {name}: {dict(counts)}")
    if errors:
        print(f"{len(errors)} problem(s):")
        for e in errors:
            print("  -", e)
        return 1
    print("OK -- CHECK_CATALOGUE.md written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
