"""Regenerate the Ontology Builder's generated documents from ``feature_model``.

Outputs (all beside this script):

* ``FEATURE_EXTRACTION.md`` — the extracted feature inventory, by area, with the
  source evidence for every feature.
* ``CAPABILITY_MAPPING.md`` — the two-way mapping between features and the
  Ontology Engineering Capability Model, plus coverage analysis per EKGF level.
* ``artifacts/feature_phases.mmd`` — Mermaid view of the phase plan.
* ``artifacts/feature_capability_map.mmd`` — Mermaid view of area → capability.

Usage::

    PYTHONPATH=. python architecture/ontology_builder/build_docs.py
"""

from __future__ import annotations

import os
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
for p in (ROOT, HERE):
    if p not in sys.path:
        sys.path.insert(0, p)

import feature_model as fm  # noqa: E402
from ontology_engineering_capabilities.capability_model import (  # noqa: E402
    CAPABILITY_BY_ID,
    CATEGORY_BY_ID,
    EKGF_LEVELS,
)

BANNER = "<!-- GENERATED by architecture/ontology_builder/build_docs.py — do not edit by hand. -->"


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def _cap(cid: str) -> str:
    c = CAPABILITY_BY_ID.get(cid)
    return f"{cid} {c.name}" if c else cid


def _evidence_md(feature: fm.Feature) -> str:
    out = []
    for e in feature.evidence:
        tool, _, rest = e.partition(":")
        if tool in fm.SOURCE_TOOL_BY_ID:
            out.append(f"**{tool}** · {rest.strip()}")
        else:
            out.append(e)
    return "<br>".join(out)


# --------------------------------------------------------------------------- #
# FEATURE_EXTRACTION.md
# --------------------------------------------------------------------------- #
def feature_extraction_md() -> str:
    L: list[str] = [BANNER, "", "# Ontology Builder — Feature Extraction", ""]
    L.append(
        "Every feature below was read out of the reference platforms' **source "
        "code**, not their marketing material. Each carries the exact service, "
        "handler, enum or extension point it came from, so the port can be "
        "checked against the original."
    )
    L.append("")
    L.append(
        f"**Totals:** {len(fm.FEATURES)} features across {len(fm.FEATURE_AREAS)} "
        f"areas, mapping to {len(fm.covered_capabilities())} of "
        f"{len(CAPABILITY_BY_ID)} capabilities in the Ontology Engineering "
        "Capability Model."
    )
    L.append("")

    # -- sources ---------------------------------------------------------- #
    L.append("## 1. Sources")
    L.append("")
    L.append("| ID | Platform | Repository | Stack | Licence |")
    L.append("|---|---|---|---|---|")
    for t in fm.SOURCE_TOOLS:
        L.append(f"| `{t.id}` | **{t.name}** | `{t.repo}` | {t.stack} | {t.licence} |")
    L.append("")
    for t in fm.SOURCE_TOOLS:
        L.append(f"**{t.name}.** {t.notes}")
        L.append("")

    # -- extraction statistics -------------------------------------------- #
    L.append("### What the extraction covered")
    L.append("")
    L.append(
        "| Platform | Surface measured | Count |\n"
        "|---|---|---|\n"
        "| VocBench 3 | Angular service classes mirroring the Semantic Turkey API | 60 |\n"
        "| VocBench 3 | distinct server operations | **781** |\n"
        "| VocBench 3 | guarded actions in `AuthorizationEvaluator` | **330** |\n"
        "| VocBench 3 | capability areas (`rdf`, `pm`, `cform`, `sys`, `rbac`, "
        "`customService`, `invokableReporter`) | 7 |\n"
        "| VocBench 3 | extension points | 15 |\n"
        "| VocBench 3 | resource-view sections | 30 |\n"
        "| VocBench 3 | integrity-constraint checks | 38 |\n"
        "| WebProtégé | action handlers | **145** |\n"
        "| WebProtégé | built-in capabilities | 53 |\n"
        "| WebProtégé | built-in roles (inheriting) | 15 |\n"
        "| WebProtégé | microservice repositories | ~15 |\n"
        "| Protégé Desktop | OSGi extension points | 24 |\n"
        "| Protégé Desktop | workspace tabs | 7 |\n"
        "| Protégé Desktop | view components | 51 |\n"
        "| Protégé Desktop | menu actions | 132 |"
    )
    L.append("")
    L.append(
        "> The Semantic Turkey **server** repository "
        "(`bitbucket.org/art-uniroma2/semanticturkey`) is not publicly clonable — "
        "it demands Bitbucket credentials. Its contract was therefore recovered "
        "in full from the VocBench 3 client, which mirrors it operation by "
        "operation, plus the peer-reviewed architecture description in the "
        "Semantic Web Journal paper. Nothing in this document depends on "
        "server-side code that was not observable."
    )
    L.append("")

    # -- source → feature coverage ---------------------------------------- #
    L.append("### Where each feature came from")
    L.append("")
    counts = {t.id: len(fm.features_from_source(t.id)) for t in fm.SOURCE_TOOLS}
    only = Counter()
    for f in fm.FEATURES:
        tools = {e.split(":", 1)[0] for e in f.evidence} & set(fm.SOURCE_TOOL_BY_ID)
        if len(tools) == 1:
            only[next(iter(tools))] += 1
        elif not tools:
            only["(new)"] += 1
    L.append("| Platform | Features drawing on it | Features drawing on it *alone* |")
    L.append("|---|---|---|")
    for t in fm.SOURCE_TOOLS:
        L.append(f"| {t.name} | {counts[t.id]} | {only[t.id]} |")
    L.append(
        f"| *(no reference tool — added here)* | {only['(new)']} | {only['(new)']} |")
    L.append("")

    # -- areas ------------------------------------------------------------ #
    L.append("## 2. Feature areas")
    L.append("")
    L.append("| Area | Name | Backend package | Features |")
    L.append("|---|---|---|---|")
    for a in fm.FEATURE_AREAS:
        L.append(f"| `{a.id}` | {a.name} | `{a.package}` | "
                 f"{len(fm.features_in_area(a.id))} |")
    L.append("")

    # -- the catalogue ---------------------------------------------------- #
    L.append("## 3. Feature catalogue")
    L.append("")
    for a in fm.FEATURE_AREAS:
        feats = fm.features_in_area(a.id)
        if not feats:
            continue
        L.append(f"### {a.id} · {a.name}")
        L.append("")
        L.append(f"*{a.description}*  ·  Backend package `{a.package}`")
        L.append("")
        for f in feats:
            L.append(f"#### {f.id} · {f.name}  `[{f.priority}]` `[{f.phase}]`")
            L.append("")
            L.append(f.description)
            L.append("")
            L.append(f"- **Source evidence:** {_evidence_md(f)}")
            L.append("- **Capabilities:** "
                     + ", ".join(_cap(c) for c in f.capabilities))
            L.append(f"- **Layers:** {', '.join(f.layers)}")
            L.append(f"- **Target:** `{f.target}`")
            if f.depends_on:
                L.append("- **Depends on:** " + ", ".join(f"`{d}`" for d in f.depends_on))
            if f.reuse:
                L.append("- **Reuse existing:** "
                         + ", ".join(f"`{r}`" for r in f.reuse))
            if f.notes:
                L.append(f"- **Note:** {f.notes}")
            L.append("")

    # -- gaps ------------------------------------------------------------- #
    L.append("## 4. Gaps in all three reference platforms")
    L.append("")
    L.append(
        "Features with no reference-tool evidence — where the merged product must "
        "be better than everything it merges:"
    )
    L.append("")
    L.append("| Feature | Why none of the three has it |")
    L.append("|---|---|")
    for f in fm.FEATURES:
        tools = {e.split(":", 1)[0] for e in f.evidence} & set(fm.SOURCE_TOOL_BY_ID)
        if tools:
            continue
        L.append(f"| **{f.id}** {f.name} | {f.notes or f.description} |")
    L.append("")
    return "\n".join(L) + "\n"


# --------------------------------------------------------------------------- #
# CAPABILITY_MAPPING.md
# --------------------------------------------------------------------------- #
def capability_mapping_md() -> str:
    L: list[str] = [BANNER, "", "# Ontology Builder — Capability Mapping", ""]
    L.append(
        "How the extracted VocBench 3, WebProtégé and Protégé Desktop features map "
        "onto the **Ontology Engineering Capability Model** "
        "(`ontology_engineering_capabilities/`), and therefore onto the **EKGF "
        "EKG Maturity Model** levels the platform is being built to reach."
    )
    L.append("")

    covered = fm.covered_capabilities()
    uncovered = sorted(set(CAPABILITY_BY_ID) - covered)
    L.append(
        f"**Coverage:** {len(covered)} of {len(CAPABILITY_BY_ID)} capabilities are "
        f"realised by at least one Ontology Builder feature."
    )
    L.append("")

    # -- level view ------------------------------------------------------- #
    L.append("## 1. Coverage by EKGF maturity level")
    L.append("")
    L.append("| Level | Capabilities | Realised | Features | Phases involved |")
    L.append("|---|---|---|---|---|")
    for lvl, lname in EKGF_LEVELS.items():
        caps = [c for c in CAPABILITY_BY_ID.values() if c.maturity_level == lvl]
        real = [c for c in caps if c.id in covered]
        feats = {f.id for c in real for f in fm.features_for_capability(c.id)}
        phases = sorted({fm.FEATURE_BY_ID[i].phase for i in feats})
        L.append(f"| **L{lvl} {lname}** | {len(caps)} | {len(real)} | "
                 f"{len(feats)} | {', '.join(phases) or '—'} |")
    L.append("")
    L.append(
        "The Level-2 (*Extensible Platform*) target of the existing application "
        "architecture (`architecture/ARCHITECTURE.md`) is met in full by phases "
        "**P0–P4**. Phases **P5–P8** carry the platform into L3–L5."
    )
    L.append("")

    # -- capability → features -------------------------------------------- #
    L.append("## 2. Capability → Ontology Builder features")
    L.append("")
    for domain in ("Business", "Technology"):
        L.append(f"### {domain} capabilities")
        L.append("")
        cats = [c for c in CATEGORY_BY_ID.values() if c.domain == domain]
        for cat in cats:
            caps = [c for c in CAPABILITY_BY_ID.values() if c.category == cat.id]
            if not caps:
                continue
            L.append(f"#### {cat.id} · {cat.name}")
            L.append("")
            L.append("| Capability | Target | Realising features | Earliest phase |")
            L.append("|---|---|---|---|")
            for c in caps:
                feats = fm.features_for_capability(c.id)
                ids = ", ".join(f"`{f.id}`" for f in feats) or "*—*"
                ph = min((f.phase for f in feats), default="—")
                L.append(f"| **{c.id}** {c.name} | L{c.maturity_level} | {ids} | {ph} |")
            L.append("")

    # -- uncovered -------------------------------------------------------- #
    L.append("## 3. Capabilities deliberately out of scope")
    L.append("")
    if uncovered:
        L.append(
            "These are realised by enterprise systems the Ontology Builder should "
            "integrate with, not replace — consistent with `architecture/"
            "ARCHITECTURE.md`, which already assigns them to COTS components "
            "(`C.FUND` Portfolio & Funding Management, `C.SKILL` Skills & Talent "
            "Management)."
        )
        L.append("")
        L.append("| Capability | Target level | Realised instead by |")
        L.append("|---|---|---|")
        hint = {
            "B.SG.4": "Portfolio/PPM tooling; the Builder contributes project "
                      "inventory and effort signals via `OB.PRJ.06` / `OB.PRJ.10`.",
            "B.VP.1": "Benefits-tracking in the enterprise's own value framework; "
                      "the Builder contributes usage and quality KPIs "
                      "(`OB.PRJ.10`, `OB.QLT.04`).",
        }
        for cid in uncovered:
            c = CAPABILITY_BY_ID[cid]
            L.append(f"| **{cid}** {c.name} | L{c.maturity_level} | "
                     f"{hint.get(cid, 'External system.')} |")
        L.append("")

    # -- feature → capability --------------------------------------------- #
    L.append("## 4. Ontology Builder features → capabilities")
    L.append("")
    L.append("| Feature | Area | Phase | Prio | Capabilities |")
    L.append("|---|---|---|---|---|")
    for f in fm.FEATURES:
        L.append(f"| **{f.id}** {f.name} | {f.area} | {f.phase} | {f.priority} | "
                 + ", ".join(f.capabilities) + " |")
    L.append("")

    # -- phase view -------------------------------------------------------- #
    L.append("## 5. What each phase unlocks")
    L.append("")
    for ph, title in fm.PHASES.items():
        feats = fm.features_in_phase(ph)
        caps = sorted({c for f in feats for c in f.capabilities})
        newly = [c for c in caps
                 if all(fm.FEATURE_BY_ID[g.id].phase >= ph
                        for g in fm.features_for_capability(c))]
        L.append(f"### {ph} — {title}")
        L.append("")
        L.append(f"- **Features:** {len(feats)} "
                 f"({sum(1 for f in feats if f.priority == 'MUST')} MUST)")
        L.append("- **Capabilities first touched here:** "
                 + (", ".join(newly) if newly else "*(deepens earlier ones)*"))
        L.append("")
    return "\n".join(L) + "\n"


# --------------------------------------------------------------------------- #
# Mermaid artifacts
# --------------------------------------------------------------------------- #
def phases_mmd() -> str:
    L = ["flowchart LR"]
    for ph, title in fm.PHASES.items():
        feats = fm.features_in_phase(ph)
        L.append(f'  {ph}["{ph}<br/>{title.split(" — ")[0]}<br/>'
                 f'{len(feats)} features"]')
    keys = list(fm.PHASES)
    for a, b in zip(keys, keys[1:]):
        L.append(f"  {a} --> {b}")
    return "\n".join(L) + "\n"


def area_capability_mmd() -> str:
    L = ["flowchart LR"]
    seen_caps: set[str] = set()
    edges: set[tuple[str, str]] = set()
    for a in fm.FEATURE_AREAS:
        L.append(f'  A{a.id}["{a.id} {a.name}"]')
        for f in fm.features_in_area(a.id):
            for c in f.capabilities:
                edges.add((a.id, c))
                seen_caps.add(c)
    for c in sorted(seen_caps):
        cap = CAPABILITY_BY_ID[c]
        cid = c.replace(".", "_")
        L.append(f'  C{cid}(["{c}<br/>{cap.name}<br/>L{cap.maturity_level}"])')
    for a, c in sorted(edges):
        L.append(f"  A{a} --> C{c.replace('.', '_')}")
    return "\n".join(L) + "\n"


# --------------------------------------------------------------------------- #
def main() -> None:
    try:
        problems = fm.validate_model(set(CAPABILITY_BY_ID))
    except Exception as exc:  # pragma: no cover
        raise SystemExit(f"model validation failed: {exc}")
    if problems:
        for p in problems:
            print("PROBLEM:", p)
        raise SystemExit("feature model is inconsistent — refusing to generate")

    art = os.path.join(HERE, "artifacts")
    os.makedirs(art, exist_ok=True)

    outputs = {
        os.path.join(HERE, "FEATURE_EXTRACTION.md"): feature_extraction_md(),
        os.path.join(HERE, "CAPABILITY_MAPPING.md"): capability_mapping_md(),
        os.path.join(art, "feature_phases.mmd"): phases_mmd(),
        os.path.join(art, "feature_capability_map.mmd"): area_capability_mmd(),
    }
    for path, text in outputs.items():
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"wrote {os.path.relpath(path, ROOT)} ({len(text):,} chars)")

    print(f"\nfeatures {len(fm.FEATURES)} | areas {len(fm.FEATURE_AREAS)} | "
          f"capabilities covered {len(fm.covered_capabilities())}"
          f"/{len(CAPABILITY_BY_ID)} | model problems 0")


if __name__ == "__main__":
    main()
